"""tasks

Revision ID: c1700017afbd
Revises: 9dc868d6099c
Create Date: 2025-12-19 14:12:11.020924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1700017afbd'
down_revision = '9dc868d6099c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caregiver_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('task_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'caregiver', ['caregiver_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_user_id_fkey'), 'caregiver', ['user_id'], ['id'])
        batch_op.drop_column('caregiver_id')

    # ### end Alembic commands ###
