"""rename notification user_id to caregiver_id

Revision ID: faa648f2f418
Revises: c1700017afbd
Create Date: 2026-01-31 17:08:15.769388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa648f2f418'
down_revision = 'c1700017afbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('user_id', new_column_name='caregiver_id', existing_type=sa.Integer())
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.create_index(batch_op.f('ix_notification_caregiver_id'), ['caregiver_id'], unique=False)
        batch_op.drop_constraint('notification_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'caregiver', ['caregiver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('caregiver_id', new_column_name='user_id', existing_type=sa.Integer())
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_user_id_fkey', 'caregiver', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_notification_caregiver_id'))
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
